robustness improvements to amplicon and metagenomics workflows

diff --git a/Metagenomics/Illumina/workflow-template/Snakefile b/Metagenomics/Illumina/workflow-template/Snakefile
--- a/Metagenomics/Illumina/workflow-template/Snakefile
+++ b/Metagenomics/Illumina/workflow-template/Snakefile
@@ -23,7 +23,7 @@ Variables that may need to be adjusted should be changed there, not here.
 # `--use-conda` – this specifies to use the conda environments included in the workflow
 # `--conda-prefix` – this allows us to point to where the needed conda environments should be stored. Including this means if we use the workflow on a different dataset somewhere else in the future, it will re-use the same conda environments rather than make new ones. The value listed here, `${CONDA_PREFIX}/envs`, is the default location for conda environments (the variable `${CONDA_PREFIX}` will be expanded to the appropriate location on whichever system it is run on).
 # `-j` – this lets us set how many jobs Snakemake should run concurrently (keep in mind that many of the thread and cpu parameters set in the config.yaml file will be multiplied by this)
-# `-p` – specifies to print out each command being run to the screen
+# `-p` – specifies to print out each command being run to the screen
 
 # See `snakemake -h` for more options and details.
 
@@ -35,6 +35,12 @@ Variables that may need to be adjusted should be changed there, not here.
 sample_IDs_file = config["sample_info_file"]
 sample_ID_list = [line.strip() for line in open(sample_IDs_file)]
 
+# making sure there are all unique names
+if len(set(sample_ID_list)) != len(sample_ID_list):
+
+    print("\n    Not all sample IDs in the " + str(config["sample_info_file"]) + " file are unique :(\n")
+    print("    Exiting for now.\n")
+    exit()
 
 ########################################
 ######## Setting up directories ########
@@ -1179,17 +1185,23 @@ rule setup_CAT_db:
         """
         mkdir -p {params.REF_DB_ROOT_DIR}
 
-        curl -L -C - -o {params.compressed_cat} {params.cat_dl_link} > {log} 2>&1
-        tar -xvzf {params.compressed_cat} -C {params.REF_DB_ROOT_DIR} > {log} 2>&1
+        printf "### Setting up CAT reference database ###\n\n" > {log} 2>&1
+
+        printf "  Downloading reference db:\n\n" >> {log} 2>&1
+        curl -L -C - -o {params.compressed_cat} {params.cat_dl_link} >> {log} 2>&1
+
+        printf "\n\n  Extracting reference db:\n\n" >> {log} 2>&1
+        tar -xvzf {params.compressed_cat} -C {params.REF_DB_ROOT_DIR} >> {log} 2>&1
+
         rm {params.compressed_cat} {params.compressed_nr_faa}
 
         touch {output.cat_db_trigger}
         """
 
 
-rule setup_KoFamScan_db:
+rule setup_KOFamScan_db:
     """
-    This rule checks for the KoFamScan db (minimally currently) and downloads if needed.
+    This rule checks for the KOFamScan db (minimally currently) and downloads if needed.
     """
 
     conda:
@@ -1206,9 +1218,31 @@ rule setup_KoFamScan_db:
         """
         mkdir -p {params.ko_db_dir}
 
-        curl -L -C - -o {params.compressed_ko_list} ftp://ftp.genome.jp/pub/db/kofam/ko_list.gz > {log} 2>&1
-        curl -L -C - -o {params.compressed_profiles} ftp://ftp.genome.jp/pub/db/kofam/profiles.tar.gz > {log} 2>&1
-        tar -xzf {params.compressed_profiles} -C {params.ko_db_dir} > {log} 2>&1
+        printf "### Setting up KOFamScan reference database ###\n\n" > {log} 2>&1
+        
+        # using https instead of ftp for those whose systems that don't have access to the ftp servers
+
+        printf "\n  Downloading ko_list file:\n\n" >> {log} 2>&1
+
+        if ! curl -L -C - --connect-timeout 15 -o {params.compressed_ko_list} ftp://ftp.genome.jp/pub/db/kofam/ko_list.gz >> {log} 2>&1
+        then
+            printf "\n\n  Downloading via http since ftp seemed to fail making the connection:\n\n"
+            curl -L -C - -o {params.compressed_ko_list} https://www.genome.jp/ftp/db/kofam/ko_list.gz >> {log} 2>&1
+        fi
+
+        printf "\n\n  Downloading profiles.tar.gz file:\n\n" >> {log} 2>&1
+
+
+        if ! curl -L -C - --connect-timeout 15 -o {params.compressed_profiles} ftp://ftp.genome.jp/pub/db/kofam/profiles.tar.gz >> {log} 2>&1
+        then
+            printf "\n\n  Downloading via http since ftp seemed to fail making the connection:\n\n"
+            curl -L -C - -o {params.compressed_profiles} https://www.genome.jp/ftp/db/kofam/profiles.tar.gz >> {log} 2>&1
+        fi
+
+        printf "\n\n  Decompressing profiles.tar.gz file:\n\n" >> {log} 2>&1
+        tar -xzf {params.compressed_profiles} -C {params.ko_db_dir} >> {log} 2>&1
+        rm {params.compressed_profiles}
+
         gunzip {params.compressed_ko_list}
 
         touch {output.kofamscan_db_trigger}
@@ -1274,11 +1308,20 @@ rule setup_humann3_dbs:
     shell:
         """
         mkdir -p {params}
+        
+        printf "### Setting up humann3 reference databases ###\n\n" > {log} 2>&1
 
-        humann3_databases --download chocophlan full {params.humann3_dbs_dir} > {log} 2>&1
-        humann3_databases --download uniref uniref90_ec_filtered_diamond {params.humann3_dbs_dir} > {log} 2>&1
-        humann3_databases --download utility_mapping full {params.humann3_dbs_dir} > {log} 2>&1
-        metaphlan --install --bowtie2db {params.metaphlan_dir} > {log} 2>&1
+        printf "  Downloading full chocophlan db:\n\n" >> {log} 2>&1
+        humann3_databases --download chocophlan full {params.humann3_dbs_dir} >> {log} 2>&1
+
+        printf "\n\n  Downloading uniref90_ec_filtered_diamond db:\n\n" >> {log} 2>&1
+        humann3_databases --download uniref uniref90_ec_filtered_diamond {params.humann3_dbs_dir} >> {log} 2>&1
+        
+        printf "\n\n  Downloading full utility_mapping db:\n\n" >> {log} 2>&1
+        humann3_databases --download utility_mapping full {params.humann3_dbs_dir} >> {log} 2>&1
+        
+        printf "\n\n  Downloading metaphlan db:\n\n" >> {log} 2>&1
+        metaphlan --install --bowtie2db {params.metaphlan_dir} >> {log} 2>&1
 
         touch {output}
         """
